from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.utils import ImageReader
from reportlab.lib import colors
import os

def generate_pdf(laporan, pdf_path):
    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4

    # === Watermark Logo TVRI ===
    logo_path = os.path.join("static", "logo-tvri.png")  # Letakkan logo di folder static
    if os.path.exists(logo_path):
        watermark = ImageReader(logo_path)
        c.saveState()
        c.translate(width/2, height/2)
        c.rotate(45)
        c.setFillAlpha(0.1)  # Transparan
        c.drawImage(watermark, -150, -150, width=300, height=300, mask='auto')
        c.restoreState()

    # === Judul ===
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width/2, height - 50, "LAPORAN PENGUKURAN TRANSMISI TVRI")

    # === Info Umum ===
    y = height - 100
    c.setFont("Helvetica", 11)
    c.drawString(50, y, f"ID Laporan: {laporan['id']}")
    y -= 20
    c.drawString(50, y, f"Tanggal: {laporan['tanggal']}")
    y -= 20
    c.drawString(50, y, f"Waktu: {laporan['waktu']}")
    y -= 20
    c.drawString(50, y, f"Petugas: {laporan['petugas']}")
    y -= 20
    c.drawString(50, y, f"Merk Transmitter: {laporan['pemancar']['merk']}")
    y -= 20
    c.drawString(50, y, f"Forward Power: {laporan['pemancar']['power_real']}")
    y -= 20
    c.drawString(50, y, f"Reflected Power: {laporan['pemancar']['reflect']}")
    y -= 30
    c.drawString(50, y, f"Downtime: {laporan['pemancar']['downtime']}")
    y -= 30

    # === Status Exciter ===
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Status Exciter:")
    y -= 20
    c.setFont("Helvetica", 11)
    c.drawString(50, y, f"Exciter A: {laporan['status']['ex_A']}")
    y -= 20
    c.drawString(50, y, f"Exciter B: {laporan['status']['ex_B']}")
    y -= 30

    # === UPS ===
    ups = laporan['kelistrikan']['UPS']
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Bagian UPS:")
    y -= 20
    c.setFont("Helvetica", 11)
    c.drawString(50, y, f"RS: {ups['RS']} | RN: {ups['RN']} | ST: {ups['ST']}")
    y -= 20
    c.drawString(50, y, f"SN: {ups['SN']} | TR: {ups['TR']} | TN: {ups['TN']}")
    y -= 20
    c.drawString(50, y, f"Frekuensi: {ups['freq']}")
    y -= 30

    # === Genset ===
    genset = laporan['kelistrikan']['Genset']
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Bagian Genset:")
    y -= 20
    c.setFont("Helvetica", 11)
    c.drawString(50, y, f"RS: {genset['RS']} | RN: {genset['RN']} | ST: {genset['ST']}")
    y -= 20
    c.drawString(50, y, f"SN: {genset['SN']} | TR: {genset['TR']} | TN: {genset['TN']}")
    y -= 20
    c.drawString(50, y, f"Frekuensi: {genset['freq']}")

    # === Footer ===
    c.setFillColor(colors.grey)
    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(width/2, 30, "Generated by TVRI KALSEL TX Monitoring System")

    c.showPage()
    c.save()
